"""empty message

Revision ID: 764d34bb98bf
Revises: 
Create Date: 2018-05-08 21:38:55.792882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764d34bb98bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('pwd', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
